# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

env:
  global:
    # Use non-interactive backend
    - MPLBACKEND: Agg
    - CYTHON_TRACE: 1

matrix:
  include:
    #- os: linux
    #  python: 3.6
    #  env:
    #    - TOXENV=pylint
    #- os: linux
    #  python: 3.6
    #  env:
    #    - TOXENV=flake8
    #- os: linux
    #  python: 3.6
    #  env:
    #    - TOXENV=bandit
    #- os: linux
    #  python: 3.6
    #  env:
    #    - TOXENV=readme
    - os: linux
      python: 3.5
      env:
        - TOXENV=short
    - os: linux
      python: 3.6
      env:
        - TOXENV=py36short
        - BUILD_LINUX=yes
    - os: linux
      python: 3.7
      env:
        - TOXENV=py36short
        - BUILD_LINUX=yes

cache: pip

before_install:
  - uname -a
  - df -h
  - ulimit -a
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source util/travis_osx_install.sh; fi
  - ccache -s
  - which python; python --version
  - pip install --upgrade pip
  - pip install --upgrade wheel
  # Set numpy version first, other packages link against it
  - pip install numpy
  - pip install Cython matplotlib nose pytest coverage codecov futures
  - set -o pipefail 
  - |
    if [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install sphinx numpydoc
    fi

script:
  - tox

after_success:
  - codecov
  # Travis CI has old gcov, needs object dir explicitly specified
  - gcov --object-directory build/tmp/pyedflib/_extensions/c/ build/tmp/pyedflib/_extensions/c/*.o
  - bash <(curl -s https://codecov.io/bash)