# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

env:
  global:
    # Use non-interactive backend
    - MPLBACKEND: Agg
    - CYTHON_TRACE: 1

matrix:
  include:
    - python: 2.7
      env:
        - PYFLAKES=1
        - PEP8=1
        - NUMPYSPEC=numpy
      before_install:
        - pip install pep8==1.6.2
        - pip install pyflakes
      script:
        - PYFLAKES_NODOCTEST=1 pyflakes pyedflib demo | grep -E -v 'unable to detect undefined names|assigned to but never used|imported but unused|redefinition of unused' > test.out; cat test.out; test \! -s test.out
        - pep8 pyedflib demo

    - python: 3.5
      env:
        - NUMPYSPEC=numpy
    - python: 3.4
      env:
        - NUMPYSPEC=numpy
    - python: 2.7
      env:
        - NUMPYSPEC="numpy==1.9.3"
    - python: 3.5
      env:
        - NUMPYSPEC=numpy
        - REFGUIDE_CHECK=1  # run doctests only

cache: pip

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install --upgrade pip
  - pip install --upgrade wheel
  # Set numpy version first, other packages link against it
  - pip install $NUMPYSPEC
  - pip install Cython matplotlib nose coverage codecov
  - set -o pipefail 
  - |
    if [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install sphinx numpydoc
    fi

script:
  # Define a fixed build dir so next step works
  - |
    if [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install -e . -v
        python util/refguide_check.py --doctests
    else
        CFLAGS="--coverage" python setup.py build --build-lib build/lib/ --build-temp build/tmp/
        nosetests build/lib/ --tests pyedflib/tests
    fi

after_success:
  - codecov
  # Travis CI has old gcov, needs object dir explicitly specified
  - gcov --object-directory build/tmp/pyedflib/_extensions/c/ build/tmp/pyedflib/_extensions/c/*.o
  - bash <(curl -s https://codecov.io/bash)